name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      deployToStage:
        description: 'Manually trigger deployment to Stage'
        required: true
        type: boolean
      deployToProd:
        description: 'Manually trigger deployment to Production'
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build
        run: echo "Building the project..."

  deploy_dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        run: echo "Deploying to Dev environment..."

  deploy_stage:
    needs: deploy_dev
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deployToStage == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Stage
        run: echo "Deploying to Stage environment..."

  deploy_prod:
    needs: deploy_stage
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deployToProd == 'true'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://production.example.com
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production environment..."
