name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      deployStage:
        description: 'Trigger Deploy to Stage'
        required: true
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
      - run: bats -v
  deploy-dev:
    runs-on: ubuntu-latest
    name: "Deploy to DEV"
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  deploy-stg:
    runs-on: ubuntu-latest
    name: "Deploy to STG"
    needs: [ deploy-dev ]
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deployToStage == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  deploy-prod:
    runs-on: ubuntu-latest
    name: "Deploy to PROD"
    needs: [ deploy-stg ]
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deployToProd == 'true'
    environment: "PROD"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

