name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
      - run: bats -v
  deploy-dev:
    runs-on: ubuntu-latest
    name: "Deploy to DEV"
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  deploy-stg:
    runs-on: ubuntu-latest
    name: "deploy-dev"
    needs: [ check-bats-version ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  deploy-prod:
    runs-on: ubuntu-latest
    name: "deploy-stg"
    needs: [ check-bats-version ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

