name: Call a reusable workflow

on:
  push:
    branches:
      - master

jobs:
  call-workflow-passing-data:
    name: "Calling workflow"
    permissions:
      contents: read
      pull-requests: write
    uses: deepakrm/shared-scripts/.github/workflows/shared/build.yaml@main
    with:
      input-1: "input-1-value"
#    secrets:
#      token: ${{ secrets.GITHUB_TOKEN }}
